# action.yml
name: "Blockless Action Setup"
description: "Installs the Blockless CLI"
inputs:
  BLOCKLESS_ACCESS_TOKEN:
    description: "Your access token for the Blockless Console"
    required: true
branding:
  icon: "box"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Install Blockless CLI
      shell: bash
      run: |-
        sudo sh -c "curl https://raw.githubusercontent.com/BlocklessNetwork/cli/main/download.sh | bash"
    - name: Authenticate With CLI
      shell: bash
      run: |-
        bls login --auth-token ${{inputs.BLOCKLESS_ACCESS_TOKEN}}
    - name: Verify Auth Token
      shell: bash
      run: |-
        bls whoami
